name: fourier

channels:
  - defaults
  - conda-forge

dependencies:
  # Computing
  - python=3.6  # PSF, https://python.org
  - pip=19  # MIT, https://pip.pypa.io
  - numpy=1.18  # BSD-3, http://numpy.scipy.org
  - scipy=1.2  # BSD-3, http://www.scipy.org
  - pandas=1.0.3  # BSD-3, http://pandas.pydata.org
  - pywavelets
  - xlrd
  - xlsxwriter
  - openpyxl
  - scikit-learn=0.24

  # Plotting
  - matplotlib
  - plotly
  - cufflinks-py

  # Jupyter
  - jupyter
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - jupytext

  # Make
  - make
  
  # DB connection
  - psycopg2

  - pip:
    - qgrid>=1.3.0  # 1.3 not yet available in conda, maybe move to conda section later
    - dash==1.18.1
    - joblib==1.0.0
